# Estadística Aplicada Grupo 043
## Karen Lorelei Cerda Roiz 
## Bianca Elizabeth Alaniz Sandoval

In [5]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [10]:
import yfinance

In [11]:
import yfinance as yf

In [13]:
import numpy as np

In [14]:
edades = [12,18,25,32,40]

In [15]:
type(edades)

list

In [33]:
#Convertir lista a arreglo de numpy
edades=np.array(edades)

In [18]:
type(edades)

numpy.ndarray

In [32]:
#promedio de todos los elementos
np.mean(edades)

25.4

In [31]:
#producto de todos los elementos
np.prod(edades)

6912000

In [30]:
#varianza poblacional
np.var(edades)

98.24000000000001

In [28]:
#varianza muestral
np.var(edades, ddof=1)

122.80000000000001

In [34]:
#desviación estandar poblacional
np.std(edades)

9.911609354691095

In [35]:
#desviación estandar muestral
np.std(edades, ddof=1)

11.081516141756055

In [36]:
#generar un vector con 9 elementos
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
#vector que empiece en 1 y termine en 9-1
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
#vector que empiece en 1 y termine en 9-1, y que vaya de 10 en 10
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [46]:
#crear vector de 10 ceros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
#crear vector de 3 unos
np.ones(3)

array([1., 1., 1.])

In [49]:
#vector de 6 nueves, o lo que queramos
np.full(6,9)

array([9, 9, 9, 9, 9, 9])

In [53]:
#esto es para que salgan los mismos num aleatorios a todos
np.random.seed(15)

#genera 10 numeros aleatorios enteros entre 0-25
np.random.randint(0,25,10)

array([ 8, 21, 12,  5, 23,  0,  7, 11, 21, 22])

In [58]:
np.random.seed(15)
aleatorios = np.random.randint(0,25,10)

In [59]:
aleatorios

array([ 8, 21, 12,  5, 23,  0,  7, 11, 21, 22])

In [62]:
#ordenar los elementos de menor a mayor
aleatorios = np.sort(aleatorios)

In [61]:
aleatorios

array([ 0,  5,  7,  8, 11, 12, 21, 21, 22, 23])

In [64]:
# nos dice la posicion 3 de la lista, iniciando de 0
aleatorios[3]

8

In [73]:
#para ver elementos de dos o mas posiciones, se pone doble corchete
aleatorios[[3,5]]

array([ 8, 12])

In [70]:
aleatorios > 5

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [72]:
#nos dice los elementos mayores a 5
aleatorios[aleatorios>5]

array([ 7,  8, 11, 12, 21, 21, 22, 23])

In [74]:
numeros = [1.23, 2.45578, 5.6888785]

In [75]:
numeros = np.array(numeros)

In [76]:
#promedio por función
np.mean(numeros)

3.1248861666666667

In [78]:
#promedio por método
numeros.mean()

3.1248861666666667

In [80]:
#con función, se convierte en arreglo, se saca el promedio y se redondea a 2 decimales
round(np.mean(np.array(numeros)),2)

3.12

In [81]:
#con método, se convierte en arreglo, se saca el promedio y se redondea a 2 decimales
np.array(numeros).mean().round(2)

3.12